from ...model import AppInfo

def render(app: AppInfo, root: str) -> str:
    return f'''# Generated by TIFEA\nprofile {app.appid} {root}/** flags=(attach_disconnected) {{\n  {root}/ r,\n  {root}/** rix,\n  /tmp/** rw,\n  owner @{root}/** rw,\n}}\n'''
